// This file is automatically generated.

#![allow(non_camel_case_types)]

use x11::xlib;

pub type xcb_bool32_t = u32;
pub type xcb_visualid_t = u32;
pub type xcb_timestamp_t = u32;
pub type xcb_keysym_t = u32;
pub type xcb_keycode_t = u8;
pub type xcb_keycode32_t = u32;
pub type xcb_button_t = u8;
pub type xcb_window_t = xlib::Window;
pub type xcb_pixmap_t = xlib::Pixmap;
pub type xcb_cursor_t = xlib::Cursor;
pub type xcb_font_t = xlib::Font;
pub type xcb_gcontext_t = xlib::GContext;
pub type xcb_colormap_t = xlib::Colormap;
pub type xcb_atom_t = xlib::Atom;

#[repr(C)]
pub union xcb_drawable_t {
    pub window: xcb_window_t,
    pub pixmap: xcb_pixmap_t,
}

#[repr(C)]
pub union xcb_fontable_t {
    pub font: xcb_font_t,
    pub gcontext: xcb_gcontext_t,
}


#[derive(Debug)]
#[repr(C)]
pub struct xcb_char2b_t {
    pub byte1: u8,
    pub byte2: u8,
}

#[derive(Debug)]
#[repr(C)]
pub struct xcb_point_t {
    pub x: i16,
    pub y: i16,
}

#[derive(Debug)]
#[repr(C)]
pub struct xcb_rectangle_t {
    pub x: i16,
    pub y: i16,
    pub width: u16,
    pub height: u16,
}

#[derive(Debug)]
#[repr(C)]
pub struct xcb_arc_t {
    pub x: i16,
    pub y: i16,
    pub width: u16,
    pub height: u16,
    pub angle1: i16,
    pub angle2: i16,
}

#[derive(Debug)]
#[repr(C)]
pub struct xcb_format_t {
    pub depth: u8,
    pub bits_per_pixel: u8,
    pub scanline_pad: u8,
    pad0: [u8; 5],
}

#[derive(Debug)]
#[repr(C)]
pub struct xcb_visualtype_t {
    pub visual_id: xcb_visualid_t,
    pub class: u8,
    pub bits_per_rgb_value: u8,
    pub colormap_entries: u16,
    pub red_mask: u32,
    pub green_mask: u32,
    pub blue_mask: u32,
    pad0: [u8; 4],
}

#[derive(Debug)]
#[repr(C)]
pub struct xcb_depth_t {
    pub depth: u8,
    pad0: [u8; 1],
    pub visuals_len: u16,
    pad1: [u8; 4],
    // list
}

#[derive(Debug)]
#[repr(C)]
pub struct xcb_screen_t {
    pub root: xcb_window_t,
    pub default_colormap: xcb_colormap_t,
    pub white_pixel: u32,
    pub black_pixel: u32,
    pub current_input_masks: u32,
    pub width_in_pixels: u16,
    pub height_in_pixels: u16,
    pub width_in_millimeters: u16,
    pub height_in_millimeters: u16,
    pub min_installed_maps: u16,
    pub max_installed_maps: u16,
    pub root_visual: xcb_visualid_t,
    pub backing_stores: u8,
    pub save_unders: u8,
    pub root_depth: u8,
    pub allowed_depths_len: u8,
    // list
}

#[derive(Debug)]
#[repr(C)]
pub struct xcb_setup_request_t {
    pub byte_order: u8,
    pad0: [u8; 1],
    pub protocol_major_version: u16,
    pub protocol_minor_version: u16,
    pub authorization_protocol_name_len: u16,
    pub authorization_protocol_data_len: u16,
    pad1: [u8; 2],
    // list
    // list
}

#[derive(Debug)]
#[repr(C)]
pub struct xcb_setup_failed_t {
    pub status: u8,
    pub reason_len: u8,
    pub protocol_major_version: u16,
    pub protocol_minor_version: u16,
    pub length: u16,
    // list
}

#[derive(Debug)]
#[repr(C)]
pub struct xcb_setup_authenticate_t {
    pub status: u8,
    pad0: [u8; 5],
    pub length: u16,
    // list
}

#[derive(Debug)]
#[repr(C)]
pub struct xcb_setup_t {
    pub status: u8,
    pad0: [u8; 1],
    pub protocol_major_version: u16,
    pub protocol_minor_version: u16,
    pub length: u16,
    pub release_number: u32,
    pub resource_id_base: u32,
    pub resource_id_mask: u32,
    pub motion_buffer_size: u32,
    pub vendor_len: u16,
    pub maximum_request_length: u16,
    pub roots_len: u8,
    pub pixmap_formats_len: u8,
    pub image_byte_order: u8,
    pub bitmap_format_bit_order: u8,
    pub bitmap_format_scanline_unit: u8,
    pub bitmap_format_scanline_pad: u8,
    pub min_keycode: xcb_keycode_t,
    pub max_keycode: xcb_keycode_t,
    pad1: [u8; 4],
    // list
    // list
    // list
}

#[derive(Debug)]
#[repr(C)]
pub struct xcb_timecoord_t {
    pub time: xcb_timestamp_t,
    pub x: i16,
    pub y: i16,
}

#[derive(Debug)]
#[repr(C)]
pub struct xcb_fontprop_t {
    pub name: xcb_atom_t,
    pub value: u32,
}

#[derive(Debug)]
#[repr(C)]
pub struct xcb_charinfo_t {
    pub left_side_bearing: i16,
    pub right_side_bearing: i16,
    pub character_width: i16,
    pub ascent: i16,
    pub descent: i16,
    pub attributes: u16,
}

#[derive(Debug)]
#[repr(C)]
pub struct xcb_str_t {
    pub name_len: u8,
    // list
}

#[derive(Debug)]
#[repr(C)]
pub struct xcb_segment_t {
    pub x1: i16,
    pub y1: i16,
    pub x2: i16,
    pub y2: i16,
}

#[derive(Debug)]
#[repr(C)]
pub struct xcb_coloritem_t {
    pub pixel: u32,
    pub red: u16,
    pub green: u16,
    pub blue: u16,
    pub flags: u8,
    pad0: [u8; 1],
}

#[derive(Debug)]
#[repr(C)]
pub struct xcb_rgb_t {
    pub red: u16,
    pub green: u16,
    pub blue: u16,
    pad0: [u8; 2],
}

#[derive(Debug)]
#[repr(C)]
pub struct xcb_host_t {
    pub family: u8,
    pad0: [u8; 1],
    pub address_len: u16,
    // list
}

